import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import bambi as bmb
import arviz as az

# ==============================================================================
# 1. DATA IMPORT & QUALTRICS CLEANING RULES
# ==============================================================================

# Step 1: Import CSV, keeping row 0 as header, and discard rows 1 & 2 (metadata)
file_path = "data.csv"
df = pd.read_csv(file_path, low_memory=False)
df = df.iloc[2:].copy() # Drops Qualtrics JSON import IDs and question texts

# Identify standard columns vs rating columns
meta_cols = ['Progress', 'Finished', 'consent_form', 'StartDate']
rating_cols = [c for c in df.columns if c.startswith(('WF-', 'WM-', 'BF-', 'BM-'))]

# Step 2: Type Conversion (CRITICAL)
# Convert progress, finished, consent, and all ratings to numeric types
for c in ['Progress', 'Finished', 'consent_form'] + rating_cols:
    df[c] = pd.to_numeric(df[c], errors='coerce')

# Step 3: Date Filter (>= March 19th, 2026)
df['StartDate'] = pd.to_datetime(df['StartDate'])
df = df[df['StartDate'] >= '2026-03-19']

# Step 4: Standardize Participant IDs
df['participantID'] = df['participantID'].replace({'ZP009': 'P009', 'Po27': 'P027'})

# Step 5 & 6: Consent & Completion Filters
df = df[df['consent_form'] == 1.0]
df = df[(df['Finished'] == 1.0) | (df['Progress'] == 100.0)]

# Step 7: Deduplication (keep most recent attempt)
df = df.sort_values(by='StartDate', ascending=False)
df = df.drop_duplicates(subset=['participantID'], keep='first')

# Step 8 & 9: Exclusion Criteria & Column Pruning
df = df[df['participantID'] != 'P046']
cols_to_keep = ['participantID'] + rating_cols
df = df[cols_to_keep]

# ==============================================================================
# 2. DATA RESHAPING & TARGET GENDER MAPPING
# ==============================================================================

# 1. Pivot to Long Format
df_long = df.melt(id_vars=['participantID'], var_name='question', value_name='rating')

# Drop unshown matrices (NAs) generated by Qualtrics Force Response randomization
df_long = df_long.dropna(subset=['rating'])

# Extract metadata using regex based on data dictionary: 
# e.g., WF-001-NR-N_1 -> targetType (WF), targetNumber (001), facialColoration (NR), shownEmotion (N), emotionChoiceID (1)
regex_pattern = r'(?P<targetType>[A-Z]{2})-(?P<targetNumber>\d+)-(?P<facialColoration>[A-Z]+)-(?P<shownEmotion>[A-Z]+)_(?P<emotionChoiceID>\d+)'
extracted_meta = df_long['question'].str.extract(regex_pattern)
df_long = pd.concat([df_long, extracted_meta], axis=1)

# 2. Target Gender Mapping
# The Chicago Face Database uses F (Female) and M (Male) in the target type (e.g., WF = White Female)
df_long['target_gender'] = df_long['targetType'].apply(lambda x: 'Female' if 'F' in str(x) else 'Male')

# 3. Congruent Rating Filter
# Map the shown emotion to the congruent choice ID. N (Neutral) uses '4' (Angry) to test H4.
congruent_map = {
    'A': '4',   # Angry -> Angry choice
    'F': '6',   # Fearful -> Scared choice
    'HC': '1',  # Happy Closed -> Happy choice
    'N': '4'    # Neutral -> Angry choice (H4)
}

# Keep only rows where the participant rating matches the congruent mapping
df_congruent = df_long[df_long.apply(lambda row: row['emotionChoiceID'] == congruent_map.get(row['shownEmotion']), axis=1)].copy()

# Optional: Export final cleaned dataset
df_congruent.to_csv("cleaned_congruent_data.csv", index=False)
print(f"Data cleaned. Final congruent observations: {len(df_congruent)}")

# ==============================================================================
# 3. STATISTICAL ANALYSIS (FREQUENTIST) - statsmodels
# ==============================================================================
print("\n--- Running Frequentist LMM ---")

# Dynamically construct formula based on whether target_gender has variance 
# (If your ongoing export currently only contains 'WF' targets, the gender term will crash the model if included)
base_formula = "rating ~ C(facialColoration) * C(shownEmotion)"
if df_congruent['target_gender'].nunique() > 1:
    base_formula += " + C(target_gender)"

# Random intercepts for participantID (groups) and targetNumber (variance components)
vc_formula = {"targetNumber": "0 + C(targetNumber)"}

try:
    freq_model = smf.mixedlm(base_formula, 
                             data=df_congruent, 
                             groups=df_congruent["participantID"], 
                             vc_formula=vc_formula)
    freq_results = freq_model.fit()
    print(freq_results.summary())
    
    # NOTE ON EMMEANS: 
    # Python does not have a direct 1:1 wrapper as magical as `emmeans`.
    # However, the simple interactions can be evaluated by inspecting the P-values 
    # and Confidence Intervals directly in the freq_results.summary() output for:
    # C(facialColoration)[T.R] interactions against the reference level.
except Exception as e:
    print(f"Frequentist Model Error: {e}")

# ==============================================================================
# 4. STATISTICAL ANALYSIS (BAYESIAN) - bambi
# ==============================================================================
print("\n--- Running Bayesian Ordered Probit ---")

# FIX: Convert the float ratings to an ordered Categorical type for Bambi's cumulative family
df_congruent['rating'] = df_congruent['rating'].astype(int)
df_congruent['rating'] = pd.Categorical(df_congruent['rating'], categories=[1, 2, 3, 4, 5], ordered=True)

# Bambi mimics lme4 formula syntax. 
# Family 'cumulative' with link 'probit' handles ordinal 1-5 scales perfectly.
bambi_formula = "rating ~ facialColoration * shownEmotion + (1|participantID) + (1|targetNumber)"
if df_congruent['target_gender'].nunique() > 1:
    bambi_formula = "rating ~ facialColoration * shownEmotion + target_gender + (1|participantID) + (1|targetNumber)"

bayes_model = bmb.Model(
    formula=bambi_formula,
    data=df_congruent,
    family="cumulative",
    link="probit"
)

# Set cores dynamically to speed up NUTS sampling.
try:
    # Run the MCMC sampler
    # Note: If it hangs or crashes your PC, lower cores=1
    bayes_results = bayes_model.fit(draws=2000, tune=1000, chains=4, cores=4)
    
    # Summary of credibility intervals (HDI)
    summary_df = az.summary(bayes_results, hdi_prob=0.95)
    print(summary_df)
    
    # Posterior Predictive Checks
    bayes_model.predict(bayes_results, kind="pps")
    az.plot_ppc(bayes_results)
except Exception as e:
    print(f"Bayesian Model Error: {e}")